### ISSUE TITLE
bot - just process additions to the _pages folder?

### ISSUE THREAD

**Issue by SaraSp** [CatalystCode/case-studies#10]
Not a big deal, but could the bot ignore changes to everything except for the _pages folder?  (Of course, we can just ignore him for non-case study additions.)

**Comment by felixrieseberg** [comment]
Good idea! For the moment, everything labeled no-review will already be ignored.



On Tue, Jul 21, 2015 at 4:53 PM -0700, "Sara Spalding" <notifications@github.com<mailto:notifications@github.com>> wrote:


Not a big deal, but could the bot ignore changes to everything except for the _pages folder? (Of course, we can just ignore him for non-case study additions.)

-

**Comment by felixrieseberg** [comment]
...this is now the case - the bot only acts if the file changed is in the _posts folder :)

**Comment by SaraSp** [comment]
Thanks bot!!

Sent from my Windows Phone

-----Original Message-----
