### ISSUE TITLE
Privacy Statement

### ISSUE THREAD

**Issue by stephbu** [CatalystCode/case-studies#36]
Work with LCA to get check we have the right privacy statement.

We currently have the Microsoft.com privacy go link, 
http://go.microsoft.com/fwlink/?LinkId=248681

We may need a different definition since the site is wholly served by a third party.  (we're nearer asp.net than *.microsoft.com)

For example http://azure.github.io/ Azure uses
http://go.microsoft.com/fwlink/p/?linkid=131004&clcid=0x409

**Comment by felixrieseberg** [comment]
We're using the same as microsoft.github.io, which seems appropriate, especially given the fact that both those links lead to the same page (http://www.microsoft.com/privacystatement/en-us/core/default.aspx).

Maybe this can be closed?

**Comment by stephbu** [comment]
Its not a bug per se, just a validation item.  Let's not second guess - LCA, I'm not a lawyer, nor do I play one on TV.  This is more a checkbox on an quick LCA review than anything else, they'll have guidance.  As you can see two different sites, two different values - they both may be correct, one of them might be wrong.  Leave it open, we can't action it directly.

**Comment by felixrieseberg** [comment]
(Closing after talking to Stephen)
