### ISSUE TITLE
WinStrap as design framework?

### ISSUE THREAD

**Issue by felixrieseberg** [CatalystCode/case-studies#46]
This is totally open for discussion, but after talking with the Windows team, I found out that they do have a "modern" theme for bootstrap, which is apparently widely used across properties - I assume that it could save us a bunch of time, too.

https://github.com/winjs/winstrap

cc @tylergibson @sarasp

**Comment by tylergibson** [comment]
Will definitely look into this, I think it could be a fantastic solution.
