### ISSUE TITLE
Need photos on overview page in the blurb about each article

### ISSUE THREAD

**Issue by joshholmes** [CatalystCode/case-studies#53]
John has asked for some type of photo on the overview page. Thoughts on where to source the image: 

- it could default to the first image in the post assuming that there is one
- It could be customer logo for those with a customer logo
- could be the author's photo

Ideally we set the order of precedent and have it default down until it finds an image.

**Comment by felixrieseberg** [comment]
This would be easy to add, but depends on where we are with the design right now. I'm happy to tackle this - @tylergibson, where are we with the design? Are you still working on it - and if so, what's the ETA?

**Comment by tylergibson** [comment]
I sent out mockups for different design directions last week, but haven't heard anything in terms of decision to move forward on anything.  I'm in a holding pattern until @SaraSp or the group gives a vote of confidence on a direction.  If we choose a direction, it will take me a day or two to pull everything into code.
